# Generated by Django 3.0.6 on 2020-05-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='br',
            name='is_boast',
            field=models.BooleanField(default=False),
        ),
    ]
