# Generated by Django 3.0.6 on 2020-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostapp', '0002_br_is_boast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='br',
            name='is_boast',
            field=models.BooleanField(),
        ),
    ]
